/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoiBoRouteImport } from './routes/noi-bo'
import { Route as IndexRouteImport } from './routes/index'

const NoiBoRoute = NoiBoRouteImport.update({
  id: '/noi-bo',
  path: '/noi-bo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noi-bo': typeof NoiBoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noi-bo': typeof NoiBoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noi-bo': typeof NoiBoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/noi-bo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/noi-bo'
  id: '__root__' | '/' | '/noi-bo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoiBoRoute: typeof NoiBoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/noi-bo': {
      id: '/noi-bo'
      path: '/noi-bo'
      fullPath: '/noi-bo'
      preLoaderRoute: typeof NoiBoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoiBoRoute: NoiBoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
